In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import math

In [4]:
dataset = pd.read_csv('E:\ELL_project\problem1\health_data.csv')
dataset = dataset.sample(frac=1)
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1:].values
datasize = X.shape[0]
X_train = X[:(datasize*7)//10,:]
y_train = y[:(datasize*7)//10,:]
X_test = X[(datasize*7)//10:,:]
y_test = y[(datasize*7)//10:,:]


In [ ]:
training_size = X_train.shape[0]
X_mean = np.sum(X_train,axis='0') / training_size
X_var = .......................................................................................................................................
X_train_reg = X_train / X_mean
y_mean = np.sum(y_train,axis='0') / training_size
y_train_reg = y_train / y_mean


In [5]:
def parsen_window(X_train_reg,X_test,y_train_reg,y_test,window_size)

[[ 64 155 335]
 [ 51 144 283]
 [ 45 139 231]
 [ 51 127 330]
 [ 23  98 229]]


In [11]:
# s = np.ones((5,3))
# divider = 2*np.ones((1,3))
# print(divider)
# print(s)
# print(s/divider)